# Generated by Django 4.2.7 on 2023-12-19 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commenting', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
