# Generated by Django 4.2.7 on 2023-12-03 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_view', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutUs',
            new_name='OurInformations',
        ),
    ]
