# Generated by Django 4.2.7 on 2023-12-12 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_view', '0006_alter_listoflevels_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=500)),
                ('choose_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_view.listoflevels')),
            ],
            options={
                'verbose_name': 'theme',
                'verbose_name_plural': 'themes',
            },
        ),
    ]
