# Generated by Django 4.2.7 on 2023-12-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_view', '0007_listoftheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='listoftheme',
            name='theme_text',
            field=models.TextField(default=''),
        ),
    ]
