# Generated by Django 4.2.7 on 2023-12-13 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_alter_useranswer_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='user_id',
            new_name='user',
        ),
    ]
