# Generated by Django 4.2.7 on 2023-12-16 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_view', '0007_listoftheme'),
        ('lesson', '0006_remove_useranswer_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500)),
                ('theme_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_view.listoftheme')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('question_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.question')),
            ],
        ),
    ]
