# Generated by Django 4.2.7 on 2023-12-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0009_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
    ]
