# Generated by Django 4.2.7 on 2023-12-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0010_answer_is_answered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_answered',
        ),
        migrations.AddField(
            model_name='question',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
    ]
