# Generated by Django 4.2.7 on 2023-12-17 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_view', '0007_listoftheme'),
        ('lesson', '0013_alter_useranswer_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theory', models.TextField()),
                ('theme_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_view.listoftheme')),
            ],
        ),
    ]
