# Generated by Django 4.2.7 on 2023-12-19 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0014_theory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_answered',
        ),
    ]
