# Generated by Django 4.2.7 on 2023-12-19 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0015_remove_question_is_answered'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Theory',
        ),
    ]
