# Generated by Django 4.2.7 on 2023-12-19 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0016_delete_theory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
        migrations.AddField(
            model_name='question',
            name='next_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lesson.question'),
        ),
    ]
